### ISSUE TITLE
NotoSansBengali: name-less "Condensed Bold" layer

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/noto-source#114]
all the glyphs in Noto Sans Bengali have a "phantom" layer which has no name:

![image](https://user-images.githubusercontent.com/6939968/38161868-8b87fd3e-34ce-11e8-8a53-2f514b663e19.png)

I noticed because glyphsLib complains about it and skips it when exporting to UFO (in which layers must have a name).

From the look of it, it seems like this should have been the missing "Condensed Bold" master layer.
In fact the Bengali, only has 5 masters defined: 4 weights, and 1 width, the Condensed (Regular).

Was it decided at some point to remove the Condensed Bold master, but somehow the layer corresponding to it was (deliberately?) left in the sources?

It'd be nice to hear from the Monotype designer.

@marekjez86 could you please put us in contact? thanks

**Comment by simoncozens** [comment]
Well, whatever reason it *was* there, it ain't any more.
