### ISSUE TITLE
Overlaps are not removed in Khmer VF

### ISSUE THREAD

**Issue by sovichet** [googlefonts/noto-source#124]
The overlaps between the stems and hair/head parts are not removed which make them not aligned well on small sizes. I don't know if the Khmer VF is ready, but it is already available on Android 8 and higher (https://android.googlesource.com/platform/external/noto-fonts/+/oreo-release/other-vf/).

Look at the ប (U+1794) letter in the screenshot from Word app on Android.

![2018-11-01 10 45 40](https://user-images.githubusercontent.com/1669566/47831556-aa47e600-ddc3-11e8-97c5-79677f05ea73.jpg)

![image](https://user-images.githubusercontent.com/1669566/47831598-c8154b00-ddc3-11e8-9d56-9b89192f49a0.png)

Similar thing happens in the preview of bold weights on Noto Sans website. The overlap in រ (U+179A) is not removed. Even the ligature in ភា, the top bar of vowel AA is a bit off from the hair of ភ.

![image](https://user-images.githubusercontent.com/1669566/47831751-83d67a80-ddc4-11e8-805b-224745dd364e.png)

**Comment by punchcutter** [comment]
This was fixed a long time ago in https://github.com/googlefonts/noto-source/commit/88c7c4de1c1341b7242ec275ff034e0c71cc068c
