### ISSUE TITLE
Noto Sans Devanagari masters with incompatible GSUBs, can't build VF

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/noto-source#135]
After updating to fontmake v2.0 (#134), we can't build a variable font from the NotoSansDevanagari-MM.plist source any longer.

This is because Noto Sans Devanagari masters have different GSUB features and fontTools.varLib (since v3.33) now includes GSUB tables of the masters when it attempts to merge them into a variable font. This is part of the "sparse masters" support added with PR https://github.com/fonttools/fonttools/pull/1368.

in this [fonttools issue](https://github.com/fonttools/fonttools/issues/1734#issuecomment-539837406), @behdad commented 

> It's okay if some of the fonts don't have a GSUB. But if they do have, they should be mergeable. Currently, that simply means they should be identical... One day we might make it generate feature variations automagically.

Honestly, before this change, I had even not realized that Noto Sans Devanagari masters had different GSUB source files.

There may be more source files that I am not aware of, which have the same issue.

Until (if ever) we make their OpenType features compatibe (or until fonttools can merge incompatible tables), we can only list and document which sources are or are not suitable for building a variable font.

**Comment by anthrotype** [comment]
just to clarify, the fact that we were able to build a VF from the same sources with the old fontmake and old fonttools doesn't mean that this VF was correct. It was simply ignoring the different master's GSUB tables and only using the default master's GSUB table.
We can't tell, without looking at the specific content of each masters' GSUB feature file, whether the differences actually _do_ make a difference.

**Comment by simoncozens** [comment]
The OT features are now compatible, so this can be built as a VF.
