### ISSUE TITLE
Compressed UFOs are not zip files

### ISSUE THREAD

**Issue by devosb** [googlefonts/noto-source#144]
The file https://github.com/googlefonts/noto-source/blob/master/src/NotoSerifKannada-MM.glyphs is from commit https://github.com/googlefonts/noto-source/commit/2a658c297ef0c9b1a8aadb6e970946b43ef50f77 which mentions that the UFOs are zipped. While they are compressed, they are not compressed by zip, but by gzip. Furthermore, the uncompressed file is a tar file, so the extension should be `.tar.gz`.

**Comment by simoncozens** [comment]
We don't (and shouldn't!) have these compressed files in the repo any more.
