### ISSUE TITLE
glyph with wrong contour order in NotoRashiHebrew

### ISSUE THREAD

**Issue by anthrotype** [googlefonts/noto-source#147]
Running [`fonttools varLib.interpolatable`](https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/varLib/interpolatable.py) script on the master TTFs generated from `src/NotoRashiHebrew-MM.glyphs` revels that glyph "tsere-hb" (unicode 05B5) has wrong component order, leading to the two contours "swapping" as the weight increases.

this can be also seen from Glyphs.app "Show Master Compatibility" UI:

![image](https://user-images.githubusercontent.com/6939968/72394160-1b826900-36ea-11ea-886c-95b696310b1d.png)

**Comment by simoncozens** [comment]
Fixed in 123010d6d0e4d7ebcd5b8a0f30a8f9ffbe4ee359
