### ISSUE TITLE
Noto Sans Myanmar can't be compiled as a variable font

### ISSUE THREAD

**Issue by jbmorizot** [googlefonts/noto-source#151]
When trying to generate the Noto Sans Myanmar as a variable font from the Glyphs source (using glyphsLib.builder.to_designspace() to get the designspace) I get an error when fontTools.varLib.build() attemps to build the variable.
The Traceback ends like this:
Seems similar to issue #135 
```
File "fontTools/Lib/fontTools/varLib/merger.py"", line 80, in mergeLists
    assert allEqualTo(out, lst, len), (len(out), [len(v) for v in lst])
AssertionError: ((20, [20, 20, 20, 20, 21, 21, 21, 21]), 'list', '.ChainSubClassRule', 'ChainSubClassSet', '[1]', 'list', '.ChainSubClassSet', 'ChainContextSubst', '[0]', 'Lookup', '[50]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GSUB', '.table', 'table_G_S_U_B_')
```

**Comment by anthrotype** [comment]
thanks for the report. Is it Myanmar (as you say in the title) or Devanagari (as you write in the body)?

**Comment by punchcutter** [comment]
Both of those have the issue of using MTI sources and having different GSUBs for different weights.

**Comment by jbmorizot** [comment]
@anthrotype It's Myanmar, sorry. I saw you already open an Issue for Devanagari Sans.

**Comment by jbmorizot** [comment]
> Both of those have the issue of using MTI sources and having different GSUBs for different weights.
Yeah I figured it out. Different number of lookups, etc. They seems really different. The good news is a lot of families using mti sources are generating VF just fine.

**Comment by simoncozens** [comment]
The OT features are now compatible, so this can be built as a VF.
