### ISSUE TITLE
Noto Nastaliq Urdu: U+0767 ARABIC LETTER NOON WITH TWO DOTS BELOW

### ISSUE THREAD

**Issue by simoncozens** [googlefonts/noto-source#167]
Shaping for this character is broken.

U+768 works as expected:
```
$ hb-shape NotoNastaliqUrdu-Regular.ttf -u '628 768'
[TahDotAboveNS=1@844,-436+0|NoonxFin=1+1535|OneDotBelowNS=0@139,-249+0|sp0=0+0|BehxIni.outT2N=0@0,688+497]
$ hb-view -O png NotoNastaliqUrdu-Regular.ttf -u '628 768'
```
![1](https://user-images.githubusercontent.com/106728/77334748-2296aa80-6d1d-11ea-8a24-69fbb921f1e4.png)

Its cousin U+767 does not:
```
$ hb-shape NotoNastaliqUrdu-Regular.ttf -u '628 767'
[uni0767=1+1764|OneDotBelowNS=0@151,-338+0|sp0=0+0|BehxIni=0+484]
$ hb-view -O png NotoNastaliqUrdu-Regular.ttf -u '628 767'
```
![2](https://user-images.githubusercontent.com/106728/77334761-26c2c800-6d1d-11ea-9938-09a205a4bcad.png)

**Comment by simoncozens** [comment]
Similarly U+06A4. 06A1 OK:
```
$ shape -u '633 6a1 633' NotoNastaliqUrdu-Regular.ttf
[SeenFin=2+2131|FehxMed.inT3outT2=1@0,932+668|sp0=0+0|SeenIni.outT3=0@0,1161+1319]
```
![shape](https://user-images.githubusercontent.com/106728/77338986-072e9e00-6d23-11ea-8b38-f5678d181ecc.png)

06A4:
```
$ shape -u '633 6a4 633' NotoNastaliqUrdu-Regular.ttf
[SeenFin=2+2131|Veh=1+2493|sp0=0+0|SeenIni=0+1244]
```
![shape](https://user-images.githubusercontent.com/106728/77339042-1f062200-6d23-11ea-9e91-16f14adc5ca6.png)

**Comment by punchcutter** [comment]
It all looks fine to me with https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/ttf/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.ttf. Which font are you using? The repo is a mess, but the latest versions of everything should be in phaseIII_only.

**Comment by simoncozens** [comment]
Sorry, yes, I had an old build. Now I have 2.0, can confirm it works.
