### ISSUE TITLE
GPOS: compiling VF from src/NotoMusic/NotoMusic.glyphs yields 'Anchor format 2 unsupported.' error

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-source#177]
fontmake: Error: In 'src/NotoMusic/NotoMusic.glyphs' -> 'master_ufo/NotoMusic-Regular.designspace': Generating fonts from Designspace failed: ('Anchor format 2 unsupported.', 'Anchor', '.EntryAnchor', 'EntryExitRecord', '[31]', 'list', '.EntryExitRecord', 'CursivePos', '[0]', 'Lookup', '[1]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')

**Comment by simoncozens** [comment]
This seems to work now. (Not that Music is a multiple master font AFAICS...)
