### ISSUE TITLE
GSUB: compiling VF from 'src/NotoSansDevanagari/NotoSansDevanagari-MM.glyphs' (UI version) yields an error

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-source#179]
fontmake: Error: In 'src/NotoSansGujarati/NotoSansGujarati-MM.glyphs' -> 'master_ufo/NotoSansGujarati.designspace': Generating fonts from Designspace failed: ((74, (74, 74, 72, 72, 74, 74, 72)), 'int', '[4]', 'list', '.LookupListIndex', 'Feature', '.Feature', 'FeatureRecord', '[11]', 'list', '.FeatureRecord', 'FeatureList', '.FeatureList', 'GSUB', '.table', 'table_G_S_U_B_')

**Comment by simoncozens** [comment]
This is fixed post-AFDKO conversion.
