### ISSUE TITLE
compiling VF from src/NotoSansJavanese/NotoSansJavanese-MM.glyphs yields an error

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-source#180]
fontmake: Error: In 'src/NotoSansJavanese/NotoSansJavanese-MM.glyphs' -> 'master_ufo/NotoSansJavanese.designspace': Generating fonts from Designspace failed: ((20, (20, 19)), 'int', '[0]', 'list', '.LookupListIndex', 'Feature', '.Feature', 'FeatureRecord', '[1]', 'list', '.FeatureRecord', 'FeatureList', '.FeatureList', 'GPOS', '.table', 'table_G_P_O_S_')

**Comment by punchcutter** [comment]
Javanese was never compatible for VF. That's why util.sh skips it for interpolation.
