### ISSUE TITLE
GSUB: compiling VF from src/NotoSansMyanmarUI/NotoSansMyanmarUI-MM.glyphs yields an error

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-source#182]
fontmake: Error: In 'src/NotoSansMyanmarUI/NotoSansMyanmarUI-MM.glyphs' -> 'master_ufo/NotoSansMyanmarUI.designspace': Generating fonts from Designspace failed: ((20, [20, 20, 20, 20, 21, 21, 21, 21]), 'list', '.ChainSubClassRule', 'ChainSubClassSet', '[1]', 'list', '.ChainSubClassSet', 'ChainContextSubst', '[0]', 'Lookup', '[50]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GSUB', '.table', 'table_G_S_U_B_')

**Comment by simoncozens** [comment]
This is fixed post-AFDKO conversion.
