### ISSUE TITLE
compiling from src/NotoSansNKo/NotoSansNKo.glyphs yields an error

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-source#183]
fontmake: Error: In 'src/NotoSansNKo/NotoSansNKo.glyphs' -> 'master_ufo/NotoSansNKo-Regular.designspace': Generating fonts from Designspace failed: (b'nko', 'str', 'ScriptRecord[0]', 'ScriptList')

**Comment by punchcutter** [comment]
Might be related to https://github.com/fonttools/fonttools/issues/1727

**Comment by iwsfutcmd** [comment]
I can't seem to replicate this bug, NotoSansNKo is building fine for me, both variable and non-variable. Is this still a problem?

**Comment by simoncozens** [comment]
I think this is fixed. (Looks like it was the short-script-tags bug linked above.)
