### ISSUE TITLE
compiling VF from src/NotoSansSyriac/NotoSansSyriac-MM.glyphs yields an error

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-source#185]
fontmake: Error: In 'src/NotoSansSyriac/NotoSansSyriac-MM.glyphs' -> 'master_ufo/NotoSansSyriac.designspace': Generating fonts from Designspace failed: fonts contains incompatible glyphs: 'uni0715.Fina.SYRJ', 'uni0715.FinaQR.SYRJ', 'uni0715.QR.SYRJ', 'uni0715.SYRJ', 'uni0716.Fina.SYRJ', 'uni0716.FinaQR.SYRJ', 'uni0716.QR.SYRJ', 'uni0716.SYRJ', 'uni0719.Fina.SYRN', 'uni0719.FinaW.SYRN', 'uni0719.SYRN', 'uni072A.Fina.SYRJ', 'uni072A.FinaQR.SYRJ', 'uni072A.QR.SYRJ', 'uni072A.SYRJ', 'uni072Auni0308.Fina.SYRJ', 'uni072Auni0308.FinaQR.SYRJ', 'uni072Auni0308.Isol.SYRJ', 'uni072Auni0308.IsolQR.SYRJ', 'uni072B', 'uni072B.Fina', 'uni072B.Fina.SYRJ', 'uni072B.Init', 'uni072B.Init.SYRJ', 'uni072B.Medi', 'uni072B.Medi.SYRJ', 'uni072B.SYRJ', 'uni072F.Fina.SYRJ', 'uni072F.FinaQR.SYRJ', 'uni072F.QR.SYRJ', 'uni072F.SYRJ'

**Comment by punchcutter** [comment]
Syriac was never compatible for VF. It will take some work to make it.
