### ISSUE TITLE
GPOS: compiling VF from src/NotoSerifMyanmar/NotoSerifMyanmar-MM.glyphs yields an error

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-source#186]
fontmake: Error: In 'src/NotoSerifMyanmar/NotoSerifMyanmar-MM.glyphs' -> 'master_ufo/NotoSerifMyanmar.designspace': Generating fonts from Designspace failed: ((3, [3, 2, 3, 3, 3, 3]), 'int', '.LangSysCount', 'Script', '.Script', 'ScriptRecord', '[0]', 'list', '.ScriptRecord', 'ScriptList', '.ScriptList', 'GPOS', '.table', 'table_G_P_O_S_')

**Comment by simoncozens** [comment]
Fixed post-AFDKO conversion.
