### ISSUE TITLE
GSUB: compiling VF from src/NotoSansGujarati/NotoSansGujarati-MM.glyphs yields an error

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-source#187]
fontmake: Error: In 'src/NotoSansGujarati/NotoSansGujarati-MM.glyphs' -> 'master_ufo/NotoSansGujarati.designspace': Generating fonts from Designspace failed: ((74, (74, 74, 72, 72, 74, 74, 72)), 'int', '[4]', 'list', '.LookupListIndex', 'Feature', '.Feature', 'FeatureRecord', '[11]', 'list', '.FeatureRecord', 'FeatureList', '.FeatureList', 'GSUB', '.table', 'table_G_S_U_B_')

**Comment by anthrotype** [comment]
Masters have different number of GSUB lookups so they can't be merged into a VF. The sources need to be fixed

**Comment by simoncozens** [comment]
Fixed post-AFDKO conversion.
