### ISSUE TITLE
Outline glitch in Noto Sans Lao

### ISSUE THREAD

**Issue by ohbendy** [googlefonts/noto-source#245]
The Black ExtraCondensed master of Lao letter oO (uni0EAD) contains an outline glitch:

![Screenshot 2020-10-17 at 13 06 49](https://user-images.githubusercontent.com/12471463/96336947-01135c80-107b-11eb-8803-c9258a7ec1d3.png)

This is present in the source Glyphs file and the compiled TTF font (version 2.00)

**Comment by nizarsq** [comment]
I believe this issue fixed. Closing this bug as fixed.
