### ISSUE TITLE
Noto siddham cannot display on ms word and adobe illustrator properly

### ISSUE THREAD

**Issue by caominhsg** [googlefonts/noto-source#272]

**Comment by marekjez86** [comment]
@caominhsg : thank you for your feedback... Could you try the font that could be downloaded from https://github.com/googlefonts/noto-fonts/tree/master/hinted/ttf/NotoSansSiddham ?

If you still have issues with this new font, could you send me photos of what wrong? and also write (or copy and paste) here the text in Siddham?

Thank you for your help...

**Comment by caominhsg** [comment]
I had installed noto font siddham and here is result

On notepad is fine and show properly but on the Adobe Illustrator is not, MS Word take long time to render and show up when I paste into ms word
I convert text from Pali to Siddham at address  https://aksharamukha.appspot.com/converter (this is not my website)

here is few pali text for you to check and test
TIṢṬA TIṢṬA
SAMAYAM ANUPĀRAYA
TATHĀGATA-HṚDAYA ŚUDDHE
VYAVAROKAYA TUMAṂ
AṢṬA BHI_ MAHĀ-DĀRUṆA BHAYEBHYAḤ
SARA SARA _PRASARA PRASARA
SARVA VARAṆA VIŚODHANI
SAMANTĀ KĀRA MAṆḌARA VIŚUDDHE
VIGATE VIGATE VIGATA
MARE VIŚODHANI
KṢIṆI KṢIṆI
SARVA PĀPA VIŚUDDHE

![image](https://user-images.githubusercontent.com/69635655/97800659-9b71c380-1c69-11eb-9499-3dddb798563b.png)
![image](https://user-images.githubusercontent.com/69635655/97800668-a593c200-1c69-11eb-8c0a-21a6ad402154.png)

**Comment by punchcutter** [comment]
This isn't a font problem, but a software problem. I will check and report the Illustrator problem.

**Comment by caominhsg** [comment]
Thanks so much

**Comment by simoncozens** [comment]
Closing as this is Adobe's issue, not Noto's.
