### ISSUE TITLE
NotoSansOldHungUI-Regular font's source has rendering command problems

### ISSUE THREAD

**Issue by tamasbartos** [googlefonts/noto-source#353]
There are rendering command problems in NotoSansOldHungUI-Regular fonts. Request date: 2021-03-16

@marekjez86 I opened this Issue because of that problems in #324 PR  must be documented.

**Comment by tamasbartos** [comment]
@marekjez86 I working on it!

**Comment by tamasbartos** [comment]
@marekjez86 I replace the UFO files with simple glyphs file. Previous PR for resolve rendering problems had got wrong letterforms. I'll replace the name NotoSansOldHungarianUI.

@marekjez86  What do you think, should I develop Old Hungarian font with minimal amount of ligatures (q, w, x, y, dz and dzs) named NotoSansOldHungarianMinimal? Tamás Rumi so agressive about these ligatures. But, I think, he wants block leading in the standard Old Hungarian font for android devices. The others warned me about it.
So what should I do in your opinion?

**Comment by marekjez86** [comment]
@tamasbartos : thank you very much! nagyon szépen köszönjük! Noto needs to support what Unicode has in https://unicode.org/charts/PDF/U10C80.pdf so we are limited to what we can do. Where could I learn about what you propose? Is this somewhere written? Is this the same as what's in the Unicode? If not why are there differences. If you have some references please point them to me. They can be in Hungarian as long as it is a text and NOT PDF or and image.

**Comment by tamasbartos** [comment]
> @tamasbartos : thank you very much! nagyon szépen köszönjük! Noto needs to support what Unicode has in https://unicode.org/charts/PDF/U10C80.pdf so we are limited to what we can do. Where could I learn about what you propose? Is this somewhere written? Is this the same as what's in the Unicode? If not why are there differences. If you have some references please point them to me. They can be in Hungarian as long as it is a text and NOT PDF or and image.

@marekjez86  Thank you for the quick answer. I'll collect links to texts on the net about this theme.

**Comment by tamasbartos** [comment]
> @tamasbartos : thank you very much! nagyon szépen köszönjük! Noto needs to support what Unicode has in https://unicode.org/charts/PDF/U10C80.pdf so we are limited to what we can do. Where could I learn about what you propose? Is this somewhere written? Is this the same as what's in the Unicode? If not why are there differences. If you have some references please point them to me. They can be in Hungarian as long as it is a text and NOT PDF or and image.

There is an article link about foreign letters in the year of 2012 in the Gábor Hosszú's submission by Miklós Szondi:
http://magyarrovas.hu/hosszu-gabor-kiserlete/
There is an article link about foreign letters by rovasinfo:
http://rovas.info/2012/11/szondi-miklos-5-tevedese/
There is the link of Gábor Hosszú's submission in the year of 2012:
https://www.unicode.org/L2/L2012/12014-n4183-hungarian.pdf
As you can see, rovasinfo do not write the full truth about foreign letters.
There isn't any valid document, which describe obligatory to use "Old Hungarian q,x,y,w,dz,dzs" letters or ligatures at all.
There sn't any valid document, which describe obligatory to use "Old Hungarian" ligatures at all.

**Comment by tamasbartos** [comment]
@marekjez86 I do not know, who asked from David Corbett ligatures, but once, when signed somebody him a mistake, he answered, if he/she doesn't like, then doesn't use. I tried extend sylable like ligatures.by logically, because I saw that some of them were developed, some of them not . It was a halfwork. I want to write that, ligatures aren't required, aren't described, just only "hisgoric symbols", which are in the chart.
That's what you were wondering?

**Comment by tamasbartos** [comment]
> @tamasbartos : thank you very much! nagyon szépen köszönjük! Noto needs to support what Unicode has in https://unicode.org/charts/PDF/U10C80.pdf so we are limited to what we can do. Where could I learn about what you propose? Is this somewhere written? Is this the same as what's in the Unicode? If not why are there differences. If you have some references please point them to me. They can be in Hungarian as long as it is a text and NOT PDF or and image.

@marekjez86  Klára Friedrich wrote me, she could send her article in word format about "Bonyhai-moga" alphabet, that really doesn't have more hundreds years old Old Hungarian "q", "y" and "x". The article was publised in www.rovasirasforrai.hu, but I can't give for you direct link. The homepage planned well, the articles' links are hidden. This theme is important?

**Comment by tamasbartos** [comment]
@marekjez86 I'll prepare the NotoSansOldHungarianUI font two or three days later, but what will happen the NotoSansOldHungarian-Regular font?

**Comment by tamasbartos** [comment]
> @tamasbartos : thank you very much! nagyon szépen köszönjük! Noto needs to support what Unicode has in https://unicode.org/charts/PDF/U10C80.pdf so we are limited to what we can do. Where could I learn about what you propose? Is this somewhere written?

Everywhere and nowhere.

>Is this the same as what's in the Unicode? 

No.

>If not why are there differences.

During the standardization users divided two parts: 1st part lost money on it, and the others need standard itself as it was used until the earlier 1800s for teaching childrens, etc.

>If you have some references please point them to me. They can be in Hungarian as long as it is a text and NOT PDF or and image.

I can't. Most of publication are already in printed books or downloadable from  electronical library of Hungarian National Library "Széchenyi" http://mek.oszk.hu

**Comment by tamasbartos** [comment]
@marekjez86 
the views of the two parties can be seen in the comment:
https://github.com/googlefonts/noto-source/issues/353#issuecomment-856535034 
 If the google translate it, please look the style of the two articles, too. (rude, offensive words)

My question: Should I give for you another links?
If yes , I need to find them, and paired them.
It was enough?
Please answer for me!

**Comment by tamasbartos** [comment]
@marekjez86 There are some unexpected issues with the fix of NotoSansOldHungarianUI font.
"Too many offcurves defined for curve." Could you help me, what does it mean?

**Comment by tamasbartos** [comment]
@marekjez86 I can now resolve "curve" problems, I think.
My question is again: what will happen NotoSansOldHungarian-regular font, which has semi-developed syllable-like ligatures? These are non-prescribed ligatures, which ones are already developed and which ones are not yet developed, too. That font has non-syllable like ligatures, which ones non-prescribed and not useful at all.

**Comment by tamasbartos** [comment]
@marekjez86 Here is a table made by András Tisza  about his syllable-like and duplicated consonant ligatures:
[Table_of_ligatures_Emese_font.pdf](https://github.com/googlefonts/noto-source/files/6639433/Table_of_ligatures_Emese_font.pdf)
Here is an explanation of main Old Hungarian vowels and consonants:
![List_Of_Main_Old_Hungarian_Letters](https://user-images.githubusercontent.com/75836867/121708858-4556df80-cad8-11eb-8dae-fbd59bf9ea89.png)
András Tisza uses consonant + vowel syllable-like ligatures and duplicated consonants because of that, as he wrote me, it optimized. Using vowel + consonant syllable-like ligatures and consonant + vowel syllable-like ligatures together, as he wrote me, can be made the text chaotic.

**Comment by tamasbartos** [comment]
@marekjez86 Ligature implementations in https://github.com/googlefonts/noto-source/issues/353?_pjax=%23js-repo-pjax-container#issuecomment-859662213 not so easy, but it is not impossible for an experienced reader to read. I can read his ligatures.

**Comment by tamasbartos** [comment]
Sorry about closing and reopening this issue.

**Comment by tamasbartos** [comment]
@marekjez86 Noto-fonts project might publish Old Hungarian font with syllable-like ligatures ( it does work https://github.com/googlefonts/noto-source/issues/353#issuecomment-859662213) and as you can read in rovas.info, they use modern letters, so their additional letters as ligatures might to be offered.

**Comment by tamasbartos** [comment]
@marekjez86 Here is the Emese font full implementation by András Tisza:
![OHu_Emese_betutabla](https://user-images.githubusercontent.com/75836867/122669623-8b89fe00-d1be-11eb-866b-9c261f6c4618.JPG)
![OHu_Emese_betutabla2](https://user-images.githubusercontent.com/75836867/122669634-95abfc80-d1be-11eb-8f91-7452dd18c6ae.JPG)
![OHu_Emese_betutabla3](https://user-images.githubusercontent.com/75836867/122669640-9b094700-d1be-11eb-9647-6979f194c843.JPG)
As you can see, on several points is different from the strict Unicode chart's letter forms. If we want to develop additional ligatures for NotoSansOldHungarian-Regular font, we might not to follow in several ligature forms of Emese font, might to follow ligature form "rules" of the NotoSansOldHungarian-regular font.
András Tisza implemented in his font the modern letters as ligatures, too.

**Comment by tamasbartos** [comment]
@marekjez86 There is a pull request #385 . Please merge it, but not publish. Please check me and write for me, which letters have still rendering problems. I can't use the  python script.

**Comment by tamasbartos** [comment]
@marekjez86  The PR #382 try to resolve NotoSansOldHungarianUI font's rendering problems.

**Comment by tamasbartos** [comment]
@marekjez86 I won't continue NotoSansOldHungarianUI development. The build process is caotical. There is an UFO command, for example : qcurve, which is in the UFO specification, but translator python script doesn't accept it. Only thing I ask for you develope UI version capital and small letters will be same baseline. UI version do not need additional ligatures.
Tamás Rumi achieved what he wanted, the Noto's Old Hungarian font development was frozen.
There are an another thing that I ask: the additional ligatured version's capital and small letters will be on the same baseline. 
I can help Noto project plan ligatures, but in that case I need freehand. I will plan and correct the several modern ligatures, ligature "q", "x", "y", "w", "dz" and "dzs", too, if you agree my help.
Regards:
Tamàs Bartos.

**Comment by tamasbartos** [comment]
@marekjez86 The ligatured Old Hungarian font needs about 300 small syllable ligatures. Must to remove left-to-right ligatures (these don't work at all.)
If you do not want that huge work, you might to add "q", "w", "x", "y" "dz" and "dzs" ligatures only. Never do halfwork!
Regards:
Tamás Bartos

**Comment by tamasbartos** [comment]
@marekjez86 I'm waiting Your answer for comment
https://github.com/googlefonts/noto-source/issues/353#issuecomment-868839239
and comment https://github.com/googlefonts/noto-source/issues/353#issuecomment-868845033

**Comment by tamasbartos** [comment]
@marekjez86 There is an attempt to resolving NotoSansOldHungarianUI in PR in #391

**Comment by tamasbartos** [comment]
@marekjez86  Plesdr help me about #391 !

**Comment by tamasbartos** [comment]
@marekjez86 I don't stop resolving this issue.
I won't include ligatures q w x y dz and dzs, because of that, you didn't signed back issue  on the noto-fonts about it.
I'll later will develop syllables. Syllable like ligatures must to be practical, readable, and aesthetic. Several ligatures in András Tisza's font are hardly readable.
I'll make testcases, because of that you could decide, you merge it or not. I don't want make difficult ligatureforms. if I can’t do some of the ligatures according to the criteria, I don’t force it.

**Comment by tamasbartos** [comment]
@marekjez86 please merge PR #398 and #399 !
PR #398 create an Old Hungarian UI (compact, without additional ligatures) font, which is publicable in noto-fonts project, I think.
 PR #399 clean up old version of Old Hungarian UI font. ( this stuffed with rendering problems)
If these PR will be merged, I start working the additional-ligatured version. (NotoSansOldHungarian font)

**Comment by tamasbartos** [comment]
@marekjez86 We  ( Old Hungarian script users and standardizers ) discussed about "modern ligatures" (q, w, y, x, dz, dzs) that aren't in the Unicode, aren't required in an official font. Without these "ligatures" we can make correct spellchecker (as hunspell library). These are non historic ligatures or letters.

**Comment by tamasbartos** [comment]
@marekjez86 @davelab6  I'm continue working on the NotoSansOldHungarian font, but unfortunately I must to go to the hospital for 4 or 5 weeks.
The ligature uni10CE5_10CE6 ("Old Hungarian sz"+"Old Hungarian t") and its ltr pair must be removed 
Because:
1. Just its author know what is that.
2. Its form is irreparable. 

I will keep all  the other ligatures, but several form of them needs to be corrected.

**Comment by tamasbartos** [comment]
@marekjez86 The Old Hungarian UI version's rendering problems are fixed. The NotoSansOldHungarianUI font is done, might to be published. I close this issue.
