### ISSUE TITLE
Noto Sans Mono U+AB60 (glyph 2193) has proportional sizes

### ISSUE THREAD

**Issue by kkartaltepe** [googlefonts/noto-source#372]
This glyph (ꭠ) appears to have an x advance of 797 (checked via ttfdump) while the rest of the glyphs are advances of 600 units (or some multiple of it). Testing on firefox shows that the character also renders as a different width as well.

![screen_20210515230511](https://user-images.githubusercontent.com/526419/118387220-05343800-b5d2-11eb-99f5-6607474e6f27.png)

**Comment by dscorbett** [comment]
Duplicate of googlefonts/noto-fonts#1785.

**Comment by kkartaltepe** [comment]
Looks like you are right, thanks ill close this one out.
