### ISSUE TITLE
The UI version of the Old Hungarian font is ready.  It can be introduced to the "noto-fonts" project page.

### ISSUE THREAD

**Issue by tamasbartos** [googlefonts/noto-source#401]
@davelab6 @marekjez86 The NotoSansOldHungarianUI font's source file is ready. May I ask that the font be published on the "noto-fonts" project page?

**Comment by tamasbartos** [comment]
@marekjez86 Marek! The original NotoSansOldHungarian font fix is ​​almost done. I won't upload the fixed source code, if you don't publish UI version. I will not work unnecessarily.

**Comment by istszab** [comment]
@marekjez86 @tamasbartos I am new in this page. What does it mean that development of Old Hungarian fonts are completely blocked, and why?

**Comment by istszab** [comment]
@marekjez86 @davelab6
The Unicode submission https://www.unicode.org/wg2/docs/n4268.pdf , based on which you have developed ligatures in your version of NotoSansOldHungarian font, has not been introduced and has been ignored. it was just an attempt at reconciliation.
Pease send a feedback to the Unicode and check me back.
I believe Your wisdom.

**Comment by tamasbartos** [comment]
@marekjez86 @davelab6 @istszab 
I just got a message,that the https://www.unicode.org/wg2/docs/n4268.pdf document unfortunately valid. Please ignore https://github.com/googlefonts/noto-source/issues/401#issuecomment-921241805
I never didn't heard about this working document before.

**Comment by tamasbartos** [comment]
@marekjez86 It seems, I must close this issue.

**Comment by tamasbartos** [comment]
@marekjez86 I reopened this issue according to document https://www.unicode.org/wg2/docs/n4268.pdf#page=7 
It said that in 6th point the followings:

6. True ligatures. In traditional manuscripts a
rather large set of ligatures is employed. These
**ligatures are optional** and should be invoked either
with  OpenType  features  or  by  specifically
requesting them from a font with the use of
U+200D ZERO WIDTH JOINER. **The list below
(reading from right to left) is not exhaustive**, but it
is based on the ligatures supported in the 8-bit
fonts made by Gábor Hosszú and Győző Libisch,
with some addition.

**Comment by tamasbartos** [comment]
@marekjez86 I think, according https://github.com/googlefonts/noto-source/issues/401#issuecomment-923124876 ,It is legal to introduce the NotoSansOldHungarianUI font.
Please, accept NotoSansOldHungarianUI font and move to "Noto-fonts" project page!

**Comment by istszab** [comment]
@marekjez86 I'm working on the original NotoSansOldHungarian-Regular font. I think about issue https://github.com/googlefonts/noto-fonts/issues/1364#issue-376193701 

https://github.com/googlefonts/noto-fonts/issues/1364#issuecomment-813088781 was just a trial only, several of subscribers can not remember this document.

I try to resolve some problems from https://github.com/googlefonts/noto-fonts/issues/2102#issue-926573413 , but I know well, that Microsoft blocks Old Hungarian scripts in MS Word and MS Edge. András Tisza asked him supporting ability of Old Hungarian script, but they answered, they lose a lot of money on Hungarian market. They answered that, if András would like to be unlocked this ability, give a large mount of money. The discussion on the MS support page blocked, too.

**Comment by tamasbartos** [comment]
@marekjez86 Do as you see fit.
