### ISSUE TITLE
Build fails because of too old ufo2ft

### ISSUE THREAD

**Issue by behdad** [googlefonts/noto-source#583]
Currently trying to build all fails in NotoMusic because NotoMusic uses `CursFeatureWriter`. However, the pinned `scripts/fontmake/requirements.txt` lists `ufo2ft >= 2.13.0`, which does not have `CursFeatureWriter`.

**Comment by behdad** [comment]
The fontmake version referenced is from 2020!  This rolls it to current fontmake tip of tree:
```
diff --git a/scripts/fontmake b/scripts/fontmake
index ef5d60785..e403c4ac8 160000
--- a/scripts/fontmake
+++ b/scripts/fontmake
@@ -1 +1 @@
-Subproject commit ef5d607853ea528f786c4903cb0fd0259b9994ea
+Subproject commit e403c4ac829e57e613032afdbcc96170d24796ba
```

**Comment by simoncozens** [comment]
I'm currently working on a whole new build process based on GitHub actions; see https://github.com/notofonts/noto-project-template

**Comment by simoncozens** [comment]
We've now deployed the new build system and this source repo is going away.
