### ISSUE TITLE
Add GlyphData.xml files

### ISSUE THREAD

**Issue by brawer** [googlefonts/noto-source#69]
@marekjez86, mind uploading Monotype’s custom GlyphData.xml files to the Noto sources? Thanks to @punchcutter, fontmake can now take a command-line argument with a custom GlyphData.xml file. See https://github.com/googlei18n/glyphsLib/pull/150.

**Comment by punchcutter** [comment]
Nothing should need a custom GlyphData.xml at this point. When there is a custom file we save the required info into the Glyphs file before delivery so that the xml isn't necessary.
